Parameters:
  DynamoDBTableName:
    Type: String
    Default: "reproject-table"
    Description: "The name of the DynamoDB table to export data from."
    PITREnabled:
      Type: String
      Default: "true"
      Description: "Enable point-in-time recovery (PITR) for the DynamoDB table."
Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref PITREnabled