Resources:
  MyCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: reproject-repo
  MySourceArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: reproject-bucket
  MyDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: reproject-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: codepipeline-deploy-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                Resource: arn:aws:cloudformation:*:*:stack/my-stack-name/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::reproject-bucket
                  - arn:aws:s3:::reproject-bucket/*

  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref MySourceArtifactBucket
        Type: S3
      Name: my-pipeline
      RoleArn: !GetAtt MyDeploymentRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                 Owner: stefanieoye
                 Repo: github-CI-CD-
                 Branch: master
                 OAuthToken: !Ref GitHubOAuthToken
                 PollForSourceChanges: 'true'
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: '1'
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: reproject-project
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuiltArtifacts
              RunOrder: '2'
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: reproject
                TemplatePath: BuiltArtifacts::my-cloudformation-template.yml
                ParameterOverrides: !Sub '{ "ArtifactBucketName": "${MySourceArtifactBucket}", "DeploymentRoleName": "${MyDeploymentRole}" }'
              InputArtifacts:
                - Name: BuiltArtifacts
              RunOrder: '3'

  MyWebhook:
                 Type: AWS::CodePipeline::Webhook
Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubWebhookSecret
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/master'
      TargetAction: SourceAction
      TargetPipeline: !Ref MyPipeline
